name: Build K Pro APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          mkdir extracted
          unzip *.zip -d extracted

      - name: Find project folder
        run: |
          PROJECT_DIR=$(find extracted -name "settings.gradle" -exec dirname {} \; | head -n 1)
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK
        run: gradle -p "$PROJECT_DIR" assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: K-Pro-APK
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
